# Gradle daemon memory
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx3072M

# Build performance
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true

# Android
android.nonTransitiveRClass=true
android.useAndroidX=true

# Kotlin
kotlin.code.style=official